export * from './tickSquare/TickSquare';
export * from './closeSquare/CloseSquare';
export * from './settings/Settings';
export * from './documentIcon/DocumentIcon';
export * from './homeIcon/HomeIcon';
export * from './searchIcon/SearchIcon';
export * from './arrowLeft/ArrowLeft';
export * from './activity/Activity';
export * from './playIcon/PlayIcon';
